default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: analytics_development

test:
  <<: *default
  database: analytics_test

production:
  <<: *default
  database: analytics_production
